# Generated by Django 5.2.10 on 2026-01-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lfa',
            name='student_outcome',
            field=models.TextField(blank=True, null=True),
        ),
    ]
