# Generated by Django 5.2.10 on 2026-01-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfa_app', '0002_lfa_student_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='lfa',
            name='activities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
