# Generated by Django 5.2.10 on 2026-01-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lfa_app', '0003_lfa_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='lfa',
            name='stakeholders',
            field=models.TextField(blank=True, null=True),
        ),
    ]
